export default {
  AUTH: {
    SET_TOKEN: "SET_TOKEN",
    REMOVE_TOKEN: "REMOVE_TOKEN",
    LOGIN: "LOGIN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED",
    LOGOUT: "LOGOUT",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS"
  }
};
